[package]
name = "screenshot"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "screenshot"
path = "src/main.rs"

[[bin]]
name = "screenshot-daemon"
path = "src/daemon.rs"

[[bin]]
name = "key-test"
path = "src/key_test.rs"

[dependencies]
arboard = "3.6.1"
captrs = "0.3.1"
chrono = "0.4.44"
eframe = { version = "0.33.3", default-features = false, features = ["x11", "glow", "default_fonts"] }
evdev = "0.13.2"
home = "0.5.12"
image = "0.25.10"
x11-dl = "2.21.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = 0
debug-assertions = false
overflow-checks = false
incremental = false
split-debuginfo = "off"
